/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package EduManager.Components;

import EduManager.Controllers.UserController;
import EduManager.Utils.PasswordValidator;
import javax.swing.JFrame;
import javax.swing.WindowConstants;
import raven.toast.Notifications;

/**
 *
 * @author cristian
 */
public class ChangePasswordComponent extends javax.swing.JFrame {

	/**
	 * Creates new form ChangePasswordComponent
	 */
	public ChangePasswordComponent() {
		initComponents();
		setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jPanel1 = new javax.swing.JPanel();
                panelRound1 = new EduManager.Components.PanelRound();
                lblUsernameContent5 = new javax.swing.JLabel();
                lblUsernameContent6 = new javax.swing.JLabel();
                lblUsernameContent7 = new javax.swing.JLabel();
                lblUsernameContent8 = new javax.swing.JLabel();
                lblUsernameContent9 = new javax.swing.JLabel();
                txtPassword = new EduManager.Components.MyTextField();
                btnChangePassword = new EduManager.Components.MyButton();
                btnCancel = new EduManager.Components.MyButton();
                lblUsernameContent10 = new javax.swing.JLabel();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                jPanel1.setBackground(new java.awt.Color(234, 244, 242));

                panelRound1.setBackground(new java.awt.Color(255, 255, 255));
                panelRound1.setRoundBottomLeft(20);
                panelRound1.setRoundBottomRight(20);
                panelRound1.setRoundTopLeft(20);
                panelRound1.setRoundTopRight(20);

                lblUsernameContent5.setFont(new java.awt.Font("CaskaydiaCove NF", 1, 24)); // NOI18N
                lblUsernameContent5.setForeground(new java.awt.Color(51, 51, 51));
                lblUsernameContent5.setText("Cambiar Contraseña");

                lblUsernameContent6.setFont(new java.awt.Font("CaskaydiaCove NF", 0, 18)); // NOI18N
                lblUsernameContent6.setForeground(new java.awt.Color(111, 111, 129));
                lblUsernameContent6.setText("La contraseña debe cumplir con lo siguiente");

                lblUsernameContent7.setFont(new java.awt.Font("CaskaydiaCove NF", 0, 18)); // NOI18N
                lblUsernameContent7.setForeground(new java.awt.Color(111, 111, 129));
                lblUsernameContent7.setText("• Al menos una mayuscula");

                lblUsernameContent8.setFont(new java.awt.Font("CaskaydiaCove NF", 0, 18)); // NOI18N
                lblUsernameContent8.setForeground(new java.awt.Color(111, 111, 129));
                lblUsernameContent8.setText("• Al menos un caracter especial");

                lblUsernameContent9.setFont(new java.awt.Font("CaskaydiaCove NF", 0, 18)); // NOI18N
                lblUsernameContent9.setForeground(new java.awt.Color(111, 111, 129));
                lblUsernameContent9.setText("• Longitud minima 8 caracteres");

                btnChangePassword.setText("Cambiar");
                btnChangePassword.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnChangePasswordActionPerformed(evt);
                        }
                });

                btnCancel.setBackground(new java.awt.Color(225, 29, 72));
                btnCancel.setText("Cancelar");
                btnCancel.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnCancelActionPerformed(evt);
                        }
                });

                lblUsernameContent10.setFont(new java.awt.Font("CaskaydiaCove NF", 0, 18)); // NOI18N
                lblUsernameContent10.setForeground(new java.awt.Color(111, 111, 129));
                lblUsernameContent10.setText("• Al menos un digito");

                javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(panelRound1);
                panelRound1.setLayout(panelRound1Layout);
                panelRound1Layout.setHorizontalGroup(
                        panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelRound1Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblUsernameContent10)
                                        .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound1Layout.createSequentialGroup()
                                                        .addComponent(btnCancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(btnChangePassword, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(txtPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(lblUsernameContent9)
                                                .addComponent(lblUsernameContent8)
                                                .addComponent(lblUsernameContent7)
                                                .addComponent(lblUsernameContent6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(lblUsernameContent5)))
                                .addContainerGap(53, Short.MAX_VALUE))
                );
                panelRound1Layout.setVerticalGroup(
                        panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelRound1Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(lblUsernameContent5)
                                .addGap(18, 18, 18)
                                .addComponent(lblUsernameContent6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblUsernameContent7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblUsernameContent8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblUsernameContent9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblUsernameContent10)
                                .addGap(18, 18, 18)
                                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(btnChangePassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(34, Short.MAX_VALUE))
                );

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(28, Short.MAX_VALUE))
                );
                jPanel1Layout.setVerticalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(24, Short.MAX_VALUE))
                );

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
		// TODO add your handling code here:
		this.setVisible(false);
        }//GEN-LAST:event_btnCancelActionPerformed

        private void btnChangePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangePasswordActionPerformed
		// TODO add your handling code here:
		String password = txtPassword.getText();
		ErrorComponent errorComponent = new ErrorComponent();
		if (!PasswordValidator.isValid(password)) {
			errorComponent.setText("La contraseña no cumple los requisitos minimos");
			Notifications.getInstance().show(Notifications.Location.BOTTOM_RIGHT, errorComponent);
			return;
		}else if(!UserController.changePassword(password)){
			errorComponent.setText("Fallo al cambiar la contraseña");
			Notifications.getInstance().show(Notifications.Location.BOTTOM_RIGHT, errorComponent);
			return;
		}
		Notifications.getInstance().show(Notifications.Location.BOTTOM_RIGHT, new SuccessComponent());
        }//GEN-LAST:event_btnChangePasswordActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(ChangePasswordComponent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(ChangePasswordComponent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(ChangePasswordComponent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(ChangePasswordComponent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new ChangePasswordComponent().setVisible(true);
			}
		});
	}

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private EduManager.Components.MyButton btnCancel;
        private EduManager.Components.MyButton btnChangePassword;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JLabel lblUsernameContent10;
        private javax.swing.JLabel lblUsernameContent5;
        private javax.swing.JLabel lblUsernameContent6;
        private javax.swing.JLabel lblUsernameContent7;
        private javax.swing.JLabel lblUsernameContent8;
        private javax.swing.JLabel lblUsernameContent9;
        private EduManager.Components.PanelRound panelRound1;
        private EduManager.Components.MyTextField txtPassword;
        // End of variables declaration//GEN-END:variables
}
