package EduManager.Components;

import EduManager.Controllers.EnrollmentController;
import EduManager.Entities.Enrollment;
import javax.swing.JPanel;

public class GroupSubjectComponent extends javax.swing.JPanel {

	EnrollmentController enrollmentController = new EnrollmentController();
	Enrollment enrollment = new Enrollment();
	int groupSubjectId;
	int studentId;

	public GroupSubjectComponent() {
		initComponents();
	}

	public void setGroupSubjectId(int groupSubjectId) {
		this.groupSubjectId = groupSubjectId;
	}

	public void setStudentId(int studentId) {
		this.studentId = studentId;
	}

	public void setDaysOfWeek(String days) {
		lblDaysOfWeek.setText(days);
	}

	public void setSubject(String subject) {
		lblSubject.setText(subject);
	}

	public void setTeacher(String teacher) {
		lblTeacher.setText(teacher);
	}

	public void setHour(String hour) {
		lblHour.setText(hour);
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                panelRound3 = new EduManager.Components.PanelRound();
                lblDaysOfWeek = new javax.swing.JLabel();
                lblSubject = new javax.swing.JLabel();
                lblTeacher = new javax.swing.JLabel();
                lblHour = new javax.swing.JLabel();
                btnDelete = new EduManager.Components.MyButton();

                setBackground(new java.awt.Color(255, 255, 255));

                panelRound3.setBackground(new java.awt.Color(17, 94, 93));
                panelRound3.setRoundBottomLeft(20);
                panelRound3.setRoundBottomRight(20);
                panelRound3.setRoundTopLeft(20);
                panelRound3.setRoundTopRight(20);
                panelRound3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                lblDaysOfWeek.setFont(new java.awt.Font("CaskaydiaCove NF", 0, 18)); // NOI18N
                lblDaysOfWeek.setForeground(new java.awt.Color(203, 213, 225));
                lblDaysOfWeek.setText("Lunes Martes Miercoles Jueves Viernes");
                panelRound3.add(lblDaysOfWeek, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

                lblSubject.setFont(new java.awt.Font("CaskaydiaCove NF", 0, 18)); // NOI18N
                lblSubject.setForeground(new java.awt.Color(255, 255, 255));
                lblSubject.setText("Matematicas Discretas");
                panelRound3.add(lblSubject, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

                lblTeacher.setFont(new java.awt.Font("CaskaydiaCove NF", 1, 18)); // NOI18N
                lblTeacher.setForeground(new java.awt.Color(255, 255, 255));
                lblTeacher.setText("Arturo Armando");
                panelRound3.add(lblTeacher, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 40));

                lblHour.setFont(new java.awt.Font("CaskaydiaCove NF", 0, 18)); // NOI18N
                lblHour.setForeground(new java.awt.Color(255, 255, 255));
                lblHour.setText("10:00:00-11:00:00");
                panelRound3.add(lblHour, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, -1, 20));

                btnDelete.setBackground(new java.awt.Color(225, 29, 72));
                btnDelete.setText("Eliminar");
                btnDelete.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnDeleteActionPerformed(evt);
                        }
                });
                panelRound3.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 410, 40));

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(panelRound3, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelRound3, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                );
        }// </editor-fold>//GEN-END:initComponents

        private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
		// TODO add your handling code here:
		JPanel parent = (JPanel) this.getParent();
		enrollment.setGroupSubjectId(groupSubjectId);
		enrollment.setStudentId(studentId);
		if (enrollmentController.deleteEnrollment(enrollment)) {
			parent.remove(this);
			parent.revalidate();
			parent.repaint();
		}
        }//GEN-LAST:event_btnDeleteActionPerformed


        // Variables declaration - do not modify//GEN-BEGIN:variables
        private EduManager.Components.MyButton btnDelete;
        private javax.swing.JLabel lblDaysOfWeek;
        private javax.swing.JLabel lblHour;
        private javax.swing.JLabel lblSubject;
        private javax.swing.JLabel lblTeacher;
        private EduManager.Components.PanelRound panelRound3;
        // End of variables declaration//GEN-END:variables
}
