/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package EduManager.Components;

import EduManager.Controllers.EnrollmentController;
import EduManager.Controllers.GroupSubjectController;
import EduManager.Entities.Enrollment;
import EduManager.Forms.StudentForm;
import java.awt.Component;
import java.util.List;
import javax.swing.JFrame;

/**
 *
 * @author cristian
 */
public class GroupStudentComponent extends javax.swing.JPanel {

	int groupSubjectId;
	int studentId;
	EnrollmentController enrollmentController = new EnrollmentController();

	public GroupStudentComponent() {
		initComponents();
	}

	public void setDaysOfWeek(String daysOfWeek) {
		lblDaysOfWeek.setText(daysOfWeek);
	}
	
	public void setTeacher(String teacher) {
		lblTeacher.setText(teacher);
	}

	public void setGroup(String group) {
		lblGroup.setText("Grupo "+group);
	}
	
	public void setVacancies(String vacancies){
		lblVacancies.setText("Vacantes "+vacancies);
	}

	public void setHour(String hour) {
		lblTeacher.setText(hour);
	}

	public void setSubject(String subject) {
		lblSubject.setText(subject);
	}

	public void setGroupSubjectId(int groupSubjectId) {
		this.groupSubjectId = groupSubjectId;
	}

	public void setStudentId(int studentId) {
		this.studentId = studentId;
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                panelRound3 = new EduManager.Components.PanelRound();
                lblDaysOfWeek = new javax.swing.JLabel();
                lblSubject = new javax.swing.JLabel();
                lblVacancies = new javax.swing.JLabel();
                lblTeacher = new javax.swing.JLabel();
                btnStudentsList = new EduManager.Components.MyButton();
                lblGroup = new javax.swing.JLabel();
                lblHour1 = new javax.swing.JLabel();

                panelRound3.setBackground(new java.awt.Color(17, 94, 93));
                panelRound3.setRoundBottomLeft(20);
                panelRound3.setRoundBottomRight(20);
                panelRound3.setRoundTopLeft(20);
                panelRound3.setRoundTopRight(20);
                panelRound3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                lblDaysOfWeek.setFont(new java.awt.Font("CaskaydiaCove NF", 0, 18)); // NOI18N
                lblDaysOfWeek.setForeground(new java.awt.Color(203, 213, 225));
                lblDaysOfWeek.setText("Lunes Martes Miercoles Jueves Viernes");
                panelRound3.add(lblDaysOfWeek, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 80, -1, -1));

                lblSubject.setFont(new java.awt.Font("CaskaydiaCove NF", 0, 18)); // NOI18N
                lblSubject.setForeground(new java.awt.Color(255, 255, 255));
                lblSubject.setText("Matematicas Discretas");
                panelRound3.add(lblSubject, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

                lblVacancies.setFont(new java.awt.Font("CaskaydiaCove NF", 0, 18)); // NOI18N
                lblVacancies.setForeground(new java.awt.Color(204, 204, 204));
                lblVacancies.setText("Vacantes 0");
                panelRound3.add(lblVacancies, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, -1, 40));

                lblTeacher.setFont(new java.awt.Font("CaskaydiaCove NF", 1, 18)); // NOI18N
                lblTeacher.setForeground(new java.awt.Color(255, 255, 255));
                lblTeacher.setText("Arturo Sorroza");
                panelRound3.add(lblTeacher, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, -1, 40));

                btnStudentsList.setBackground(new java.awt.Color(255, 255, 255));
                btnStudentsList.setForeground(new java.awt.Color(102, 102, 102));
                btnStudentsList.setText("Matricular");
                btnStudentsList.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnStudentsListActionPerformed(evt);
                        }
                });
                panelRound3.add(btnStudentsList, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 20, 180, 40));

                lblGroup.setFont(new java.awt.Font("CaskaydiaCove NF", 0, 18)); // NOI18N
                lblGroup.setForeground(new java.awt.Color(13, 148, 136));
                lblGroup.setText("GRUPO 4SA");
                panelRound3.add(lblGroup, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, 40));

                lblHour1.setFont(new java.awt.Font("CaskaydiaCove NF", 1, 18)); // NOI18N
                lblHour1.setForeground(new java.awt.Color(255, 255, 255));
                lblHour1.setText("10:00-11:00");
                panelRound3.add(lblHour1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 40));

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(panelRound3, javax.swing.GroupLayout.PREFERRED_SIZE, 1206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelRound3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                );
        }// </editor-fold>//GEN-END:initComponents

        private void btnStudentsListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudentsListActionPerformed
		// TODO add your handling code here:

		Enrollment enrollment = new Enrollment();
		enrollment.setStudentId(studentId);
		enrollment.setGroupSubjectId(groupSubjectId);

		if (enrollmentController.addEnrollment(enrollment)) {
			// Obtener el panel padre y llamar al método fillPanelSchedule
			Component parent = this.getParent();
			while (parent != null && !(parent instanceof StudentForm)) {
				parent = parent.getParent();
			}

			if (parent != null) {
				((StudentForm) parent).fillPanelSchedule();
			}
		}
        }//GEN-LAST:event_btnStudentsListActionPerformed


        // Variables declaration - do not modify//GEN-BEGIN:variables
        private EduManager.Components.MyButton btnStudentsList;
        private javax.swing.JLabel lblDaysOfWeek;
        private javax.swing.JLabel lblGroup;
        private javax.swing.JLabel lblHour1;
        private javax.swing.JLabel lblSubject;
        private javax.swing.JLabel lblTeacher;
        private javax.swing.JLabel lblVacancies;
        private EduManager.Components.PanelRound panelRound3;
        // End of variables declaration//GEN-END:variables
}
