/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package EduManager.Components;

import EduManager.Controllers.EnrollmentController;
import EduManager.Entities.Enrollment;
import java.util.List;
import javax.swing.JFrame;

/**
 *
 * @author cristian
 */
public class GroupComponent extends javax.swing.JPanel {

	int groupSubjectId;
	EnrollmentController enrollmentController = new EnrollmentController();

	
	public GroupComponent() {
		initComponents();
	}
	
	public void setDaysOfWeek(String daysOfWeek){
		lblDaysOfWeek.setText(daysOfWeek);
	}
	
	public void setGroup(String group){
		lblGroup.setText(group);
	}
	
	public void setHour(String hour){
		lblHour.setText(hour);
	}
	
	public void setSubject(String subject){
		lblSubject.setText(subject);
	}
	
	public void setGroupSubjectId(int groupSubjectId){
		this.groupSubjectId = groupSubjectId;
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                panelRound3 = new EduManager.Components.PanelRound();
                lblDaysOfWeek = new javax.swing.JLabel();
                lblSubject = new javax.swing.JLabel();
                lblGroup = new javax.swing.JLabel();
                lblHour = new javax.swing.JLabel();
                btnStudentsList = new EduManager.Components.MyButton();

                panelRound3.setBackground(new java.awt.Color(17, 94, 93));
                panelRound3.setRoundBottomLeft(20);
                panelRound3.setRoundBottomRight(20);
                panelRound3.setRoundTopLeft(20);
                panelRound3.setRoundTopRight(20);
                panelRound3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                lblDaysOfWeek.setFont(new java.awt.Font("CaskaydiaCove NF", 0, 18)); // NOI18N
                lblDaysOfWeek.setForeground(new java.awt.Color(203, 213, 225));
                lblDaysOfWeek.setText("Lunes Martes Miercoles Jueves Viernes");
                panelRound3.add(lblDaysOfWeek, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 80, -1, -1));

                lblSubject.setFont(new java.awt.Font("CaskaydiaCove NF", 0, 18)); // NOI18N
                lblSubject.setForeground(new java.awt.Color(255, 255, 255));
                lblSubject.setText("Matematicas Discretas");
                panelRound3.add(lblSubject, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

                lblGroup.setFont(new java.awt.Font("CaskaydiaCove NF", 0, 18)); // NOI18N
                lblGroup.setForeground(new java.awt.Color(13, 148, 136));
                lblGroup.setText("GRUPO 4SA");
                panelRound3.add(lblGroup, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, 40));

                lblHour.setFont(new java.awt.Font("CaskaydiaCove NF", 0, 18)); // NOI18N
                lblHour.setForeground(new java.awt.Color(255, 255, 255));
                lblHour.setText("10:00-11:00");
                panelRound3.add(lblHour, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 40));

                btnStudentsList.setBackground(new java.awt.Color(255, 255, 255));
                btnStudentsList.setForeground(new java.awt.Color(102, 102, 102));
                btnStudentsList.setText("Ver");
                btnStudentsList.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnStudentsListActionPerformed(evt);
                        }
                });
                panelRound3.add(btnStudentsList, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 20, 180, 40));

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelRound3, javax.swing.GroupLayout.DEFAULT_SIZE, 1334, Short.MAX_VALUE)
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelRound3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                );
        }// </editor-fold>//GEN-END:initComponents

        private void btnStudentsListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudentsListActionPerformed
                // TODO add your handling code here:
		
		StudentsList studentsList = new StudentsList();
		studentsList.setGroupSubjectId(groupSubjectId);
		studentsList.setGroup(lblGroup.getText());
		studentsList.setSubject(lblSubject.getText());
		studentsList.fillGroupsList();
		studentsList.setVisible(true);
        }//GEN-LAST:event_btnStudentsListActionPerformed


        // Variables declaration - do not modify//GEN-BEGIN:variables
        private EduManager.Components.MyButton btnStudentsList;
        private javax.swing.JLabel lblDaysOfWeek;
        private javax.swing.JLabel lblGroup;
        private javax.swing.JLabel lblHour;
        private javax.swing.JLabel lblSubject;
        private EduManager.Components.PanelRound panelRound3;
        // End of variables declaration//GEN-END:variables
}
