/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package EduManager.Components;

import EduManager.Controllers.EnrollmentController;
import EduManager.Controllers.GroupSubjectController;
import EduManager.Controllers.StudentController;
import EduManager.Entities.Enrollment;
import EduManager.Entities.GroupSubject;
import EduManager.Entities.Student;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.WindowConstants;

public class StudentsList extends javax.swing.JFrame {

	private List<Enrollment> enrollments;
	private final EnrollmentController enrollmentController = new EnrollmentController();
	private final StudentController studentController = new StudentController();
	private int groupSubjectId;

	public StudentsList() {
		initComponents();
		setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
	}

	public void setEnrollments(List<Enrollment> enrollments) {
		this.enrollments = enrollments;
	}
	
	public void setNumberOfStudents(int numberStudents){
		lblNumberStudents.setText(numberStudents + " estudiantes");
	}
	
	public void setGroupSubjectId(int groupSubjectId){
		this.groupSubjectId = groupSubjectId;
	}

	public void fillGroupsList() {
		panelGroups.removeAll();
		enrollments = enrollmentController.getEnrollmentsByGroupSubjectId(groupSubjectId);
		for (Enrollment enrollment : enrollments) {
			Student student = studentController.getStudentById(enrollment.getStudentId());

			StudentComponent studentComponent = new StudentComponent();
			studentComponent.setEmail(student.getEmail());
			studentComponent.setFirstName(student.getFirstName());
			studentComponent.setLastName(student.getLastName());
			studentComponent.setPhoneNumber(student.getPhoneNumber());
			studentComponent.setSemester(student.getSemester());
			studentComponent.setStudentId(student.getUserId());
			studentComponent.setStudentImagePath(student.getImagePath());
			panelGroups.add(studentComponent);
		}
		
		panelGroups.revalidate();
		panelGroups.repaint();
	}
	
	public void setGroup(String group){
		lblGroupName.setText(group);
	}
	
	public void setSubject(String subject){
		lblSubject.setText(subject);
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jPanel1 = new javax.swing.JPanel();
                panelRound1 = new EduManager.Components.PanelRound();
                jScrollPane1 = new javax.swing.JScrollPane();
                panelGroups = new javax.swing.JPanel();
                jPanel2 = new javax.swing.JPanel();
                lblName = new javax.swing.JLabel();
                lblName1 = new javax.swing.JLabel();
                lblName2 = new javax.swing.JLabel();
                lblName3 = new javax.swing.JLabel();
                lblName4 = new javax.swing.JLabel();
                lblName5 = new javax.swing.JLabel();
                lblName6 = new javax.swing.JLabel();
                jSeparator1 = new javax.swing.JSeparator();
                panelRound5 = new EduManager.Components.PanelRound();
                lblGroupName = new javax.swing.JLabel();
                lblNumberStudents = new javax.swing.JLabel();
                lblSubject = new javax.swing.JLabel();
                jLabel1 = new javax.swing.JLabel();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setBackground(new java.awt.Color(234, 244, 242));

                jPanel1.setBackground(new java.awt.Color(234, 244, 242));

                panelRound1.setBackground(new java.awt.Color(255, 255, 255));
                panelRound1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 102), 1, true));
                panelRound1.setRoundBottomLeft(20);
                panelRound1.setRoundBottomRight(20);
                panelRound1.setRoundTopLeft(20);
                panelRound1.setRoundTopRight(20);
                panelRound1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
                jScrollPane1.setBorder(null);

                panelGroups.setBackground(new java.awt.Color(255, 255, 255));
                panelGroups.setLayout(new java.awt.GridLayout(22, 2, 20, 20));
                jScrollPane1.setViewportView(panelGroups);

                panelRound1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 65, 1840, 760));

                jPanel2.setBackground(new java.awt.Color(255, 255, 255));

                lblName.setFont(new java.awt.Font("CaskaydiaCove NF", 0, 18)); // NOI18N
                lblName.setForeground(new java.awt.Color(0, 102, 102));
                lblName.setText("Foto");

                lblName1.setFont(new java.awt.Font("CaskaydiaCove NF", 0, 18)); // NOI18N
                lblName1.setForeground(new java.awt.Color(0, 102, 102));
                lblName1.setText("Nombre");

                lblName2.setFont(new java.awt.Font("CaskaydiaCove NF", 0, 18)); // NOI18N
                lblName2.setForeground(new java.awt.Color(0, 102, 102));
                lblName2.setText("Id");

                lblName3.setFont(new java.awt.Font("CaskaydiaCove NF", 0, 18)); // NOI18N
                lblName3.setForeground(new java.awt.Color(0, 102, 102));
                lblName3.setText("Apellido");

                lblName4.setFont(new java.awt.Font("CaskaydiaCove NF", 0, 18)); // NOI18N
                lblName4.setForeground(new java.awt.Color(0, 102, 102));
                lblName4.setText("Email");

                lblName5.setFont(new java.awt.Font("CaskaydiaCove NF", 0, 18)); // NOI18N
                lblName5.setForeground(new java.awt.Color(0, 102, 102));
                lblName5.setText("Telefono");

                lblName6.setFont(new java.awt.Font("CaskaydiaCove NF", 0, 18)); // NOI18N
                lblName6.setForeground(new java.awt.Color(0, 102, 102));
                lblName6.setText("Semestre");

                javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
                jPanel2.setLayout(jPanel2Layout);
                jPanel2Layout.setHorizontalGroup(
                        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(lblName)
                                .addGap(44, 44, 44)
                                .addComponent(lblName2)
                                .addGap(104, 104, 104)
                                .addComponent(lblName1)
                                .addGap(160, 160, 160)
                                .addComponent(lblName3)
                                .addGap(167, 167, 167)
                                .addComponent(lblName4)
                                .addGap(258, 258, 258)
                                .addComponent(lblName5)
                                .addGap(69, 69, 69)
                                .addComponent(lblName6)
                                .addContainerGap(519, Short.MAX_VALUE))
                );
                jPanel2Layout.setVerticalGroup(
                        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblName)
                                        .addComponent(lblName2)
                                        .addComponent(lblName1)
                                        .addComponent(lblName4)
                                        .addComponent(lblName5)
                                        .addComponent(lblName6)
                                        .addComponent(lblName3))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );

                panelRound1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1790, 30));

                jSeparator1.setBackground(new java.awt.Color(0, 102, 102));
                panelRound1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 1850, 10));

                panelRound5.setBackground(new java.awt.Color(13, 148, 136));
                panelRound5.setRoundBottomLeft(30);
                panelRound5.setRoundBottomRight(30);
                panelRound5.setRoundTopLeft(30);
                panelRound5.setRoundTopRight(30);
                panelRound5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                lblGroupName.setFont(new java.awt.Font("CaskaydiaCove NF", 1, 48)); // NOI18N
                lblGroupName.setForeground(new java.awt.Color(255, 255, 255));
                lblGroupName.setText("Grupo 4SA");
                panelRound5.add(lblGroupName, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 15, -1, -1));

                lblNumberStudents.setFont(new java.awt.Font("CaskaydiaCove NF", 1, 24)); // NOI18N
                lblNumberStudents.setForeground(new java.awt.Color(250, 250, 250));
                lblNumberStudents.setText("40 estudiantes Inscritos");
                panelRound5.add(lblNumberStudents, new org.netbeans.lib.awtextra.AbsoluteConstraints(1510, 130, -1, -1));

                lblSubject.setFont(new java.awt.Font("CaskaydiaCove NF", 1, 24)); // NOI18N
                lblSubject.setForeground(new java.awt.Color(250, 250, 250));
                lblSubject.setText("Programacion Orientada a Objetos");
                panelRound5.add(lblSubject, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

                jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EduManager/Images/college.png"))); // NOI18N
                panelRound5.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1660, 10, 130, 90));

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(panelRound5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(panelRound1, javax.swing.GroupLayout.DEFAULT_SIZE, 1866, Short.MAX_VALUE))
                                .addContainerGap(26, Short.MAX_VALUE))
                );
                jPanel1Layout.setVerticalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(panelRound5, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, 843, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20))
                );

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(StudentsList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(StudentsList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(StudentsList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(StudentsList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new StudentsList().setVisible(true);
			}
		});
	}

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JLabel jLabel1;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel jPanel2;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JSeparator jSeparator1;
        private javax.swing.JLabel lblGroupName;
        private javax.swing.JLabel lblName;
        private javax.swing.JLabel lblName1;
        private javax.swing.JLabel lblName2;
        private javax.swing.JLabel lblName3;
        private javax.swing.JLabel lblName4;
        private javax.swing.JLabel lblName5;
        private javax.swing.JLabel lblName6;
        private javax.swing.JLabel lblNumberStudents;
        private javax.swing.JLabel lblSubject;
        private javax.swing.JPanel panelGroups;
        private EduManager.Components.PanelRound panelRound1;
        private EduManager.Components.PanelRound panelRound5;
        // End of variables declaration//GEN-END:variables
}
