/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package EduManager.Components;

import raven.swing.AvatarIcon;

/**
 *
 * @author cristian
 */
public class StudentComponent extends javax.swing.JPanel {

	/**
	 * Creates new form StudentComponent
	 */
	public StudentComponent() {
		initComponents();
		AvatarIcon icon = new AvatarIcon(getClass().getResource("/EduManager/Images_profile/profile.png"), 40, 40, 999);
		lblProfileImage.setIcon(icon);
	}
	
	public void setEmail(String email){
		lblEmail.setText(email);
	}
	
	public void setPhoneNumber(String phoneNumber){
		lblPhoneNumber.setText(phoneNumber);
	}
	
	public void setStudentId(int studentId){
		lblId.setText(studentId+"");
	}
	
	public void setFirstName(String name){
		lblFirstName.setText(name);
	}
	
	public void setSemester(int semester){
		lblSemester.setText(""+semester);
	}
	
	public void setLastName(String lastName){
		lblLastName.setText(lastName);
	}
	
	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                panelRound4 = new EduManager.Components.PanelRound();
                lblProfileImage = new javax.swing.JLabel();
                lblSemester = new javax.swing.JLabel();
                lblId = new javax.swing.JLabel();
                lblFirstName = new javax.swing.JLabel();
                lblLastName = new javax.swing.JLabel();
                lblEmail = new javax.swing.JLabel();
                lblPhoneNumber = new javax.swing.JLabel();
                panelRound1 = new EduManager.Components.PanelRound();
                lblPhoneNumber1 = new javax.swing.JLabel();
                panelRound2 = new EduManager.Components.PanelRound();
                lblPhoneNumber2 = new javax.swing.JLabel();
                panelRound3 = new EduManager.Components.PanelRound();
                lblPhoneNumber3 = new javax.swing.JLabel();
                myButtonOutLine1 = new EduManager.Components.MyButtonOutLine();
                jSeparator2 = new javax.swing.JSeparator();

                setBackground(new java.awt.Color(255, 255, 255));

                panelRound4.setBackground(new java.awt.Color(255, 255, 255));
                panelRound4.setRoundBottomLeft(20);
                panelRound4.setRoundBottomRight(20);
                panelRound4.setRoundTopLeft(20);
                panelRound4.setRoundTopRight(20);
                panelRound4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
                panelRound4.add(lblProfileImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 40, 40));

                lblSemester.setFont(new java.awt.Font("CaskaydiaCove NF", 0, 18)); // NOI18N
                lblSemester.setForeground(new java.awt.Color(111, 111, 129));
                lblSemester.setText("4");
                panelRound4.add(lblSemester, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 20, 20, -1));

                lblId.setFont(new java.awt.Font("CaskaydiaCove NF", 0, 18)); // NOI18N
                lblId.setForeground(new java.awt.Color(111, 111, 129));
                lblId.setText("22161096");
                panelRound4.add(lblId, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, -1));

                lblFirstName.setFont(new java.awt.Font("CaskaydiaCove NF", 0, 18)); // NOI18N
                lblFirstName.setForeground(new java.awt.Color(111, 111, 129));
                lblFirstName.setText("Cristian Neftali");
                panelRound4.add(lblFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 180, -1));

                lblLastName.setFont(new java.awt.Font("CaskaydiaCove NF", 0, 18)); // NOI18N
                lblLastName.setForeground(new java.awt.Color(111, 111, 129));
                lblLastName.setText("Hernandez Ramirez");
                panelRound4.add(lblLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, 190, -1));

                lblEmail.setFont(new java.awt.Font("CaskaydiaCove NF", 0, 18)); // NOI18N
                lblEmail.setForeground(new java.awt.Color(111, 111, 129));
                lblEmail.setText("cristian0402218@gmail.com");
                panelRound4.add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 20, 290, -1));

                lblPhoneNumber.setFont(new java.awt.Font("CaskaydiaCove NF", 0, 18)); // NOI18N
                lblPhoneNumber.setForeground(new java.awt.Color(111, 111, 129));
                lblPhoneNumber.setText("9513135154");
                panelRound4.add(lblPhoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 20, 120, -1));

                panelRound1.setBackground(new java.awt.Color(129, 205, 198));
                panelRound1.setRoundBottomLeft(20);
                panelRound1.setRoundBottomRight(20);
                panelRound1.setRoundTopLeft(20);
                panelRound1.setRoundTopRight(20);

                lblPhoneNumber1.setFont(new java.awt.Font("CaskaydiaCove NF", 0, 18)); // NOI18N
                lblPhoneNumber1.setForeground(new java.awt.Color(8, 85, 78));
                lblPhoneNumber1.setText("U2 90");

                javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(panelRound1);
                panelRound1.setLayout(panelRound1Layout);
                panelRound1Layout.setHorizontalGroup(
                        panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelRound1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblPhoneNumber1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );
                panelRound1Layout.setVerticalGroup(
                        panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(lblPhoneNumber1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                );

                panelRound4.add(panelRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1440, 20, 70, 30));

                panelRound2.setBackground(new java.awt.Color(129, 205, 198));
                panelRound2.setRoundBottomLeft(20);
                panelRound2.setRoundBottomRight(20);
                panelRound2.setRoundTopLeft(20);
                panelRound2.setRoundTopRight(20);

                lblPhoneNumber2.setFont(new java.awt.Font("CaskaydiaCove NF", 0, 18)); // NOI18N
                lblPhoneNumber2.setForeground(new java.awt.Color(8, 85, 78));
                lblPhoneNumber2.setText("U3 80");

                javax.swing.GroupLayout panelRound2Layout = new javax.swing.GroupLayout(panelRound2);
                panelRound2.setLayout(panelRound2Layout);
                panelRound2Layout.setHorizontalGroup(
                        panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelRound2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblPhoneNumber2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );
                panelRound2Layout.setVerticalGroup(
                        panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(lblPhoneNumber2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                );

                panelRound4.add(panelRound2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1530, 20, 70, 30));

                panelRound3.setBackground(new java.awt.Color(129, 205, 198));
                panelRound3.setRoundBottomLeft(20);
                panelRound3.setRoundBottomRight(20);
                panelRound3.setRoundTopLeft(20);
                panelRound3.setRoundTopRight(20);

                lblPhoneNumber3.setFont(new java.awt.Font("CaskaydiaCove NF", 0, 18)); // NOI18N
                lblPhoneNumber3.setForeground(new java.awt.Color(8, 85, 78));
                lblPhoneNumber3.setText("U1 80");

                javax.swing.GroupLayout panelRound3Layout = new javax.swing.GroupLayout(panelRound3);
                panelRound3.setLayout(panelRound3Layout);
                panelRound3Layout.setHorizontalGroup(
                        panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelRound3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblPhoneNumber3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );
                panelRound3Layout.setVerticalGroup(
                        panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblPhoneNumber3, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                );

                panelRound4.add(panelRound3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1350, 20, 70, 30));

                myButtonOutLine1.setText("Calificar");
                panelRound4.add(myButtonOutLine1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1680, 20, -1, 30));

                jSeparator2.setBackground(new java.awt.Color(0, 102, 102));

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(panelRound4, javax.swing.GroupLayout.PREFERRED_SIZE, 1801, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 1814, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(panelRound4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                );
        }// </editor-fold>//GEN-END:initComponents


        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JSeparator jSeparator2;
        private javax.swing.JLabel lblEmail;
        private javax.swing.JLabel lblFirstName;
        private javax.swing.JLabel lblId;
        private javax.swing.JLabel lblLastName;
        private javax.swing.JLabel lblPhoneNumber;
        private javax.swing.JLabel lblPhoneNumber1;
        private javax.swing.JLabel lblPhoneNumber2;
        private javax.swing.JLabel lblPhoneNumber3;
        private javax.swing.JLabel lblProfileImage;
        private javax.swing.JLabel lblSemester;
        private EduManager.Components.MyButtonOutLine myButtonOutLine1;
        private EduManager.Components.PanelRound panelRound1;
        private EduManager.Components.PanelRound panelRound2;
        private EduManager.Components.PanelRound panelRound3;
        private EduManager.Components.PanelRound panelRound4;
        // End of variables declaration//GEN-END:variables
}
