/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package EduManager.Forms;

import javax.swing.JFrame;

/**
 *
 * @author cristian
 */
public class SupportFrame extends javax.swing.JFrame {

	/**
	 * Creates new form ChangePasswordFrame
	 */
	public SupportFrame() {
		initComponents();
		setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
	}
	
	public void setEmail(String email){
		lblEmail.setText(email);
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jPanel1 = new javax.swing.JPanel();
                panelRound1 = new EduManager.Components.PanelRound();
                lblUsernameContent7 = new javax.swing.JLabel();
                panelRound2 = new EduManager.Components.PanelRound();
                lblUsernameContent4 = new javax.swing.JLabel();
                jLabel1 = new javax.swing.JLabel();
                lblEmail = new javax.swing.JLabel();
                myButton1 = new EduManager.Components.MyButton();
                lblUsernameContent6 = new javax.swing.JLabel();
                linePanel1 = new EduManager.Components.LinePanel();
                linePanel2 = new EduManager.Components.LinePanel();
                lblUsernameContent8 = new javax.swing.JLabel();
                jTextField1 = new javax.swing.JTextField();
                jScrollPane1 = new javax.swing.JScrollPane();
                jTextArea1 = new javax.swing.JTextArea();
                btnClose = new EduManager.Components.MyButton();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setBackground(new java.awt.Color(234, 244, 242));

                jPanel1.setBackground(new java.awt.Color(234, 244, 242));

                panelRound1.setBackground(new java.awt.Color(255, 255, 255));
                panelRound1.setRoundBottomLeft(30);
                panelRound1.setRoundBottomRight(30);
                panelRound1.setRoundTopLeft(30);
                panelRound1.setRoundTopRight(30);
                panelRound1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                lblUsernameContent7.setFont(new java.awt.Font("CaskaydiaCove NF", 0, 18)); // NOI18N
                lblUsernameContent7.setForeground(new java.awt.Color(111, 111, 129));
                lblUsernameContent7.setText("Tu email ...");
                panelRound1.add(lblUsernameContent7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 260, -1));

                panelRound2.setBackground(new java.awt.Color(17, 94, 93));
                panelRound2.setRoundTopLeft(30);
                panelRound2.setRoundTopRight(30);

                lblUsernameContent4.setFont(new java.awt.Font("CaskaydiaCove NF", 0, 18)); // NOI18N
                lblUsernameContent4.setForeground(new java.awt.Color(255, 255, 255));
                lblUsernameContent4.setText("Email to support@eduManager.com");

                jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\cristian\\Github\\Java\\EduManager\\src\\EduManager\\Icons\\send.png")); // NOI18N

                javax.swing.GroupLayout panelRound2Layout = new javax.swing.GroupLayout(panelRound2);
                panelRound2.setLayout(panelRound2Layout);
                panelRound2Layout.setHorizontalGroup(
                        panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelRound2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblUsernameContent4, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(370, Short.MAX_VALUE))
                );
                panelRound2Layout.setVerticalGroup(
                        panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelRound2Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel1)
                                        .addComponent(lblUsernameContent4))
                                .addContainerGap(14, Short.MAX_VALUE))
                );

                panelRound1.add(panelRound2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 50));

                lblEmail.setFont(new java.awt.Font("CaskaydiaCove NF", 0, 18)); // NOI18N
                lblEmail.setForeground(new java.awt.Color(51, 51, 51));
                lblEmail.setText("cristian@gmail.com");
                panelRound1.add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, -1, -1));

                myButton1.setBackground(new java.awt.Color(17, 94, 93));
                myButton1.setText("Enviar");
                panelRound1.add(myButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 420, 200, 50));

                lblUsernameContent6.setFont(new java.awt.Font("CaskaydiaCove NF", 0, 18)); // NOI18N
                lblUsernameContent6.setForeground(new java.awt.Color(111, 111, 129));
                lblUsernameContent6.setText("De");
                panelRound1.add(lblUsernameContent6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

                javax.swing.GroupLayout linePanel1Layout = new javax.swing.GroupLayout(linePanel1);
                linePanel1.setLayout(linePanel1Layout);
                linePanel1Layout.setHorizontalGroup(
                        linePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
                );
                linePanel1Layout.setVerticalGroup(
                        linePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
                );

                panelRound1.add(linePanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 119, 720, -1));

                javax.swing.GroupLayout linePanel2Layout = new javax.swing.GroupLayout(linePanel2);
                linePanel2.setLayout(linePanel2Layout);
                linePanel2Layout.setHorizontalGroup(
                        linePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
                );
                linePanel2Layout.setVerticalGroup(
                        linePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
                );

                panelRound1.add(linePanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 179, 720, -1));

                lblUsernameContent8.setFont(new java.awt.Font("CaskaydiaCove NF", 0, 18)); // NOI18N
                lblUsernameContent8.setForeground(new java.awt.Color(111, 111, 129));
                lblUsernameContent8.setText("Asunto");
                panelRound1.add(lblUsernameContent8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 90, -1));

                jTextField1.setBackground(new java.awt.Color(255, 255, 255));
                jTextField1.setFont(new java.awt.Font("CaskaydiaCove NF", 0, 18)); // NOI18N
                jTextField1.setForeground(new java.awt.Color(51, 51, 51));
                jTextField1.setBorder(null);
                panelRound1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 650, 60));

                jTextArea1.setBackground(new java.awt.Color(255, 255, 255));
                jTextArea1.setColumns(20);
                jTextArea1.setFont(new java.awt.Font("CaskaydiaCove NF", 0, 18)); // NOI18N
                jTextArea1.setForeground(new java.awt.Color(51, 51, 51));
                jTextArea1.setRows(5);
                jTextArea1.setBorder(null);
                jScrollPane1.setViewportView(jTextArea1);

                panelRound1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 720, 160));

                btnClose.setBackground(new java.awt.Color(225, 29, 72));
                btnClose.setText("Cancelar y Cerrar este panel");
                btnClose.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnCloseActionPerformed(evt);
                        }
                });
                panelRound1.add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 420, 300, 50));

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(26, Short.MAX_VALUE))
                );
                jPanel1Layout.setVerticalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(33, Short.MAX_VALUE))
                );

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
                // TODO add your handling code here:
		this.setVisible(false);
        }//GEN-LAST:event_btnCloseActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(SupportFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(SupportFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(SupportFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(SupportFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new SupportFrame().setVisible(true);
			}
		});
	}

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private EduManager.Components.MyButton btnClose;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JTextArea jTextArea1;
        private javax.swing.JTextField jTextField1;
        private javax.swing.JLabel lblEmail;
        private javax.swing.JLabel lblUsernameContent4;
        private javax.swing.JLabel lblUsernameContent6;
        private javax.swing.JLabel lblUsernameContent7;
        private javax.swing.JLabel lblUsernameContent8;
        private EduManager.Components.LinePanel linePanel1;
        private EduManager.Components.LinePanel linePanel2;
        private EduManager.Components.MyButton myButton1;
        private EduManager.Components.PanelRound panelRound1;
        private EduManager.Components.PanelRound panelRound2;
        // End of variables declaration//GEN-END:variables
}
